---
title: "Death trends"
output:
  html_document:
    theme: cosmo
    mathjax: null
    self_contained: false
    toc: true
---

```{css, echo=F}
pre.r > code {white-space: pre;}
```

```{r setup, message=F}
library(CausalImpact)
library(gghighlight)
library(scales)
library(zoo)
```

```{r logic}
go <- function(deaths) {
  deaths <- na.trim(deaths)
  data <- deaths
  data$Cumulative <- ave(data,
                         format(time(data), "%Y"),
                         FUN=cumsum)
  names(data) <- c("Monthly", "Cumulative")
  data <- fortify.zoo(data, melt=T)
  data$Year <- format(data$Index, "%Y")
  data$Month <- as.numeric(format(data$Index, "%m"))
  data$Index <- NULL

  p <- function() {
    ggplot(data) +
      geom_line(aes(x=Month, y=Value, group=Year, color=Year)) +
      gghighlight(Year %in% c("2020", "2019"),
                  use_group_by=F,
                  calculate_per_facet=T) +
      facet_wrap(~Series, dir="v", scales="free_y") +
      xlab("") + ylab("Deaths") +
      scale_y_continuous(labels=scales::label_number_si()) +
      scale_x_discrete(limits=month.abb, guide=guide_axis(check.overlap=T)) +
      theme_bw(base_size=15)
  }

  print(suppressMessages(p()))

  data <- deaths
  if (any(is.na(data))) {
    message("Interpolated missing data.")
    data <- na.approx(data, na.rm=T)
  }

  tryCatch({
    pre.period <- c(start(data), as.yearmon("Dec 2019"))
    post.period <- c(as.yearmon("Jan 2020"), end(data))
    model.args <- list(niter=1000, nseasons=12)

    impact <- CausalImpact(data,
                           pre.period,
                           post.period,
                           model.args=model.args)

    print(plot(impact) +
            scale_y_continuous(labels=scales::label_number_si()) +
            ylab("Deaths"))
    cat(impact$report)

    impact$summary["Cumulative",]
  }, error=message)
}

total <- function(deaths) {
  deaths <- na.approx(deaths)
  data <- zoo(cbind(rowSums(deaths)), time(deaths))
  names(data) <- "V1"
  go(data)
}

by.region <- function(deaths) {
  excess <- data.frame()
  for (region in names(deaths)) {
    nice.region <- gsub("[.]", " ", region)
    cat(paste("\n\n####", nice.region, "\n\n"))
    data <- subset(deaths, select=region)
    row <- go(data)
    if (!is.null(row)) {
      row.names(row) <- c(nice.region)
      excess <- rbind(excess, row)
    }
  }
  excess
}

plot.excess <- function(excess, level="####") {
  excess$Country <- row.names(excess)
  excess <- excess[order(-excess$RelEffect),]

  cat(paste("\n\n", level, " Relative\n\n", sep=""))
  p <- ggplot(excess, aes(x=Country, y=RelEffect)) +
    geom_col() +
    geom_errorbar(aes(ymin=RelEffect.lower, ymax=RelEffect.upper)) +
    gghighlight(p < 0.05 & !(RelEffect.lower <= 0 & 0 <= RelEffect.upper)) +
    scale_y_continuous(labels=scales::label_percent()) +
    xlab("") + ylab("") +
    theme_minimal() +
    coord_flip()

  print(p)

  excess <- excess[order(-excess$AbsEffect),]

  cat(paste("\n\n", level, " Absolute\n\n", sep=""))
  p <- ggplot(excess, aes(x=Country, y=AbsEffect)) +
    geom_col() +
    geom_errorbar(aes(ymin=AbsEffect.lower, ymax=AbsEffect.upper)) +
    gghighlight(p < 0.05 & !(AbsEffect.lower <= 0 & 0 <= AbsEffect.upper)) +
    scale_y_continuous(labels=scales::label_number_si()) +
    xlab("") + ylab("") +
    theme_minimal() +
    coord_flip()

  print(p)
}
```

```{r data}
get.sheet.url <- function(gid) {
  paste("https://docs.google.com/spreadsheets/d/e/2PACX-1vQfgIZSsUrFzbmVK0hjbTjvY2TGI75FRkrU8rGKpLebZnfFFBCvFyI1zPgUE3uivCOmbOKOYJWyYUiQ/pub?gid=",
        gid,
        "&single=true&output=csv",
        sep="")
}

au.deaths <- read.csv.zoo(get.sheet.url("1434566235"), FUN=as.yearmon)
nz.deaths <- read.csv.zoo(get.sheet.url("894713646"), FUN=as.yearmon)
us.deaths <- read.csv.zoo(get.sheet.url("1095978846"), FUN=as.yearmon)
uk.deaths <- read.csv.zoo(get.sheet.url("0"), FUN=as.yearmon)

countries <- data.frame()
```

Australia {.tabset}
-------------------

### Regional {.tabset .tabset-pills}

```{r au.region, results="asis"}
au.region <- by.region(au.deaths)
```

### Country

```{r au.country, results="asis"}
countries <- rbind(countries, Australia=total(au.deaths))
```

### Excess deaths per region {.tabset .tabset-pills}

```{r au.excess, results="asis"}
plot.excess(au.region)
```

New Zealand {.tabset}
---------------------

### Regional {.tabset .tabset-pills}

```{r nz.region, results="asis"}
nz.region <- by.region(nz.deaths)
```

### Country

```{r nz.country, results="asis"}
countries <- rbind(countries, `New Zealand`=total(nz.deaths))
```

### Excess deaths per region {.tabset .tabset-pills}

```{r nz.excess, results="asis"}
plot.excess(nz.region)
```

UK {.tabset}
------------

### Regional {.tabset .tabset-pills}

```{r uk.region, results="asis"}
uk.region <- by.region(uk.deaths)
```

### Country

```{r uk.country, results="asis"}
countries <- rbind(countries, `United Kingdom`=total(uk.deaths))
```

### Excess deaths per region {.tabset .tabset-pills}

```{r uk.excess, results="asis"}
plot.excess(uk.region)
```

US {.tabset}
------------

Note: I couldn't find historical data for Puerto Rico, so it's excluded from
impact analysis.

### Regional {.tabset .tabset-pills}

```{r us.region, results="asis"}
us.region <- by.region(us.deaths)
```

### Country

```{r us.country, results="asis"}
countries <- rbind(countries,
                   `United States`=total(subset(us.deaths, select=-Puerto.Rico)))
```

### Excess deaths per region {.tabset .tabset-pills}

```{r us.excess, results="asis"}
plot.excess(us.region)
```

# Excess deaths per country {.tabset}
```{r country.excess, results="asis"}
plot.excess(countries, level="##")
```
